Birthdays:
  "9-15": ["Daphnee", "Lain"]
  "12-30": ["Alice"]
DiscordEnabled: false
DiscordWebhook: "DiscordWebhookAddress"
TwilioEnable: false
TwilioAccountSid: "TwilioAccountSid"
TwilioAuthToken : "TwilioAuthToken"
TwilioFromNumber: "Twilio Phone Number message are sent from"
TwilioToNumber: "Phone Number this app will send message to"
City: "Breda"
